trigger:
  batch: true
  branches:
    include:
    - master

pr:
  autoCancel: true

variables:
  azureSubscription: Visual Studio Enterprise(e97d8b6e-d05b-4507-9c06-f7b528f65f7d)

stages:
# Build
- stage: Build
  jobs:
  - job: Build
  - template: templates/build.yml

- stage: Staging
  jobs:
  - template: templates/release.yml
    parameters:
      azureSubscription: $(azureSubscription)
      environment: staging

- stage: Proudction
  jobs:
  - template: templates/release.yml
    parameters:
      azureSubscription: $(azureSubscription)
      environment: production
