name: $(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: 'Ubuntu 16.04'

stages:
- stage: Verify
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: GitVersion@4
      inputs:
      displayName: Determine Semantic Version

    - script: |
        echo "##vso[build.updatebuildnumber]$(GITVERSION_FullSemVer)"
      displayName: Update build number

    - script: |
        docker run --rm \
          --volume=`pwd`/src:/srv/jekyll \
          jekyll/builder:stable \
          jekyll build
      displayName: Build Jekyll site

# Staging release
- stage: Staging
  jobs:
  - template: templates/release.yml
    parameters:
      azureSubscription: $(sandboxAzureSubscription)

# Production release
- stage: Production
  jobs:
  - template: templates/release.yml
    parameters:
      azureSubscription: $(productionAzureSubscription)
