parameters:
  containerRegistryName:

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    # Run GitVersion
    - task: GitVersion@5
      inputs:
        runtime: core
      displayName: Determine Semantic Version

    # Update build number to GitVersion semver
    - script: echo '##vso[build.updatebuildnumber]$(GitVersion.FullSemVer)'
      displayName: Update build number

    # Compile blog
    - task: AzureCLI@2
      inputs:
        displayName: Compile Blog
        azureSubscription: 'Visual Studio Enterprise(e97d8b6e-d05b-4507-9c06-f7b528f65f7d)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Fail on errors, output every command and result to the log
          set -e -x

          # Log in to our container registry
          az acr login -n ${{ parameters.containerRegistryName }}

          # Pull the most recent builder image which we'll use as a cache
          docker pull ${{ parameters.containerRegistryName }}.azurecr.io/blog:latest

          # Create the builder image
          docker build \
              --target build \
              --cache-from ${{ parameters.containerRegistryName }}.azurecr.io/blog:latest \
              -t builder .

          # Tag and push the latest builder version for later cacheign
          docker tag builder ${{containerRegistryName}}.azurecr.io/blog:latest
          docker push ${{containerRegistryName}}.azurecr.io/blog:latest

          # Build the blog
          docker run \
              --mount type=bind,source=$(Build.ArtifactStagingDirectory),target=/workspaces/blog/src/_site \
              builder

    # Publish the app as an artifact
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: blog
