parameters:
  azureSubscription:
  containerRegistryName:

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    # Run GitVersion
    - task: GitVersion@5
      inputs:
        runtime: core
      displayName: Determine Semantic Version

    # Update build number to GitVersion semver
    - script: echo '##vso[build.updatebuildnumber]$(GitVersion.FullSemVer)'
      displayName: Update build number

    # Compile blog
    - task: AzureCLI@2
      inputs:
        displayName: Compile Blog
        azureSubscription: ${{ parameters.azureSubscription }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Fail on errors, output every command and result to the log
          set -e -x

          # Log in to our container registry
          az acr login -n ${{ parameters.containerRegistryName }}

          # Pull the most recent builder image which we'll use as a cache, ignore misses
          docker pull ${{ parameters.containerRegistryName }}.azurecr.io/blog:latest || true

          # Create the builder image
          docker build \
              --target build \
              --cache-from ${{ parameters.containerRegistryName }}.azurecr.io/blog:latest \
              -t builder .

          # Tag and push the latest builder version for later cacheign
          docker tag builder ${{ parameters.containerRegistryName }}.azurecr.io/blog:latest
          docker push ${{ parameters.containerRegistryName }}.azurecr.io/blog:latest

          # Build the blog
          docker run \
              --mount type=bind,source=$(Build.ArtifactStagingDirectory),target=/workspaces/blog/src/_site \
              builder

    # Publish the app as an artifact
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: blog
