parameters:
  environment:

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    # Run GitVersion
    - task: GitVersion@5
      inputs:
        runtime: core
      displayName: Determine Semantic Version

    # Update build number to GitVersion semver
    - script: |
        echo '##vso[build.updatebuildnumber]$(GitVersion.FullSemVer)'
      displayName: Update build number

    # Compile jekyll site
    - script: |
        set -e -x
        docker run --rm \
          --volume=`pwd`/src:/srv/jekyll \
          --volume=$(Build.ArtifactStagingDirectory):/srv/jekyll/_site \
          jekyll/builder:stable \
          jekyll build
      displayName: Build Jekyll site

    # Publish the app as an artifact
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: blog
