parameters:
  azureSubscription:
  environment:
  terraformStorageAccountName:

jobs:
- job: Deploy
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    # Load artifacts
    - download: current
      artifact: blog
    
    # Apply terraform
    - task: terraformcli@0
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform/
        script: |
          # Fail on errors, output every command and result to the log
          set -e -x

          # Generate a Terraform plan
          terraform plan \
            -var environment="${{ parameters.environment }}" \
            -out=${{ parameters.environment }}.tfplan \
            -input=false 

          # Apply Terraform Template
          terraform apply ${{ parameters.environment }}.tfplan

    # Update storage account var
    - script: |
        # Fail on errors, output every command and result to the log
        set -e -x
        echo "##vso[task.setvariable variable=storageAccountName]`terraform output storage_account`"
      displayName: Load details from terraform infrastructure
    
    # AZCopy release
    - task: AzureFileCopy@3
      inputs:
        SourcePath: $(Pipeline.Workspace)/blog
        azureSubscription: ${{ parameters.azureSubscription }}
        Destination: AzureBlob
        storage: $(storageAccountName)
        ContainerName: $web
        displayName: Deploy to blob storage