parameters:
  azureSubscription:
  environment:
  terraformStorageAccountName:

jobs:
- job: Deploy
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    # Load artifacts
    - download: current
      artifact: blog

    # Apply terraform
    - task: terraformcli@0
      inputs:
        targetAzureSubscription: ${{ parameters.azureSubscription }}
        targetStorageAccountName: '${{ parameters.terraformStorageAccountName }}'
        backendStateFileKey: '${{ parameters.environment }}.terraform.tfstate'
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform/
        script: |
          # Fail on errors, output every command and result to the log
          set -e -x

          # Generate a Terraform plan
          terraform plan \
            -var environment="${{ parameters.environment }}" \
            -out=${{ parameters.environment }}.tfplan \
            -input=false 

          # Apply Terraform Template
          terraform apply ${{ parameters.environment }}.tfplan

          # Get output
          STORAGE_ACCOUNT=`terraform output storage_account`

          # Set storageAccountName variable from terraform output
          echo "##vso[task.setvariable variable=storageAccountName]$STORAGE_ACCOUNT"

    # The Azure CLI __MUST__ be installed and available at the following path before using `az storage blob sync` 
    #
    # See: https://github.com/Azure/azure-cli/issues/10024
    #
    - script: |
        wget -O azcopy.tar.gz https://aka.ms/downloadazcopylinux64
        tar -xf azcopy.tar.gz
        sudo ./install.sh
        sudo ln -s /usr/bin/azcopy /usr/local/bin/azcopy
      displayName: Install AZCopy

    # Configure storage account and upload files
    - task: AzureCLI@1
      inputs:
        azureSubscription: 'Visual Studio Enterprise(e97d8b6e-d05b-4507-9c06-f7b528f65f7d)'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Fail on errors, output every command and result to the log
          set -e -x

          # Configure static sites
          az storage blob service-properties update --account-name $(storageAccountName) --static-website  --index-document index.html --404-document 404.html

          # Upload files
          az storage blob sync \
            -s $(Pipeline.Workspace)/blog \
            -c \$web \
            --account-name $(storageAccountName)

