# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate-v2]


pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true
  category: published

encoding: utf-8

source: .
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Joey Lorich
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://nandomoreira.me
baseurl: "/"

google_analytics: UA-52446115-1
repo: http://github.com/jlorich/blog
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Joey Lorich
  job: "@Microsoft"
  bio: "I'm an IoT, DevOps, distributed systems, and organizational processes nerd"
  thumb: /images/author.jpg
  email: joseph@lorich.me
  url: https://josephlorich.net
  github: https://github.com/jlorich
  twitter: https://twitter.com/joeylorich
  linkedin: https://linkedin.com/in/jlorich

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
