source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem 'jekyll', '~> 4.0', '>= 4.0.1'
gem 'sass', '~> 3.7', '>= 3.7.4'
gem 'json', '~> 2.3'


# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "bourbon", "~>4.3"
  gem "jekyll-feed", "~>0.6"
  gem 'jekyll-paginate-v2', '~> 3.0'
  gem 'jekyll-compose', '~> 0.12.0'
  gem 'rouge', '~> 3.19'
end
