name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  # Build the blog
  jekyll_build:
    runs-on: ubuntu-latest
    container: jekyll/builder:4.1.0
    name: Jekyll Build
    steps:
      # Checkout Source
      - uses: actions/checkout@v2

      # Build Blog
      - name: Build
        run: cd src && jekyll build
      
      # Upload site
      - uses: actions/upload-artifact@v2
        with:
          name: blog
          path: src/_site/

  # Upload the blog to staging
  staging_deploy:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    name: Staging Deploy
    steps:
      # Download site
      - uses: actions/upload-artifact@v2
        with:
          name: blog
    
      # Deploy site to Azure Static Web Apps
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_HILL_076F7201E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "src/_site"

  # Upload the blog to prod
  prod_deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Staging Deploy
    steps:
      # Download site
      - uses: actions/upload-artifact@v2
        with:
          name: blog
    
      # Deploy site to Azure Static Web Apps
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_HILL_076F7201E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "src/_site"
