name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  # Build the blog site
  jekyll_build:
    runs-on: ubuntu-latest
    container: jekyll/builder:4.1.0
    name: Jekyll Build Job
    steps:
      # Checkout Source
      - uses: actions/checkout@v2

      # Build Blog
      - name: Build
        run: cd src && jekyll build
      
      # Upload site
      - uses: actions/upload-artifact@v2
        with:
          name: blog
          path: src/_site/

  # Deploy to static websites
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      # Download site
      - uses: actions/download-artifact@v2
        with:
          name: blog
      
      # Deploy
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_DESERT_090BB0F1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: .

  # Close pending static site content on PR close
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_DESERT_090BB0F1E }}
          action: "close"
